### PR TITLE
Small change in how config information is passed in.

### PR DESCRIPTION
**Pull request by peetucket**
Remove need to have configuration parameters in a YML file, allow a generic hash to be passed in instead.  Adjust readme file to describe changed usage.

### CODE REVIEW

**Comment by cgs** [comment]
I like the change. A couple of suggesions though. Can you 1) fix/update the broken tests in user_store_spec and 2) fix the indentation in the readme? Maybe something like this would be easier to read:

```
config = {
  'username' => 'YOUR_USERNAME',
  'password' => 'YOUR_PASSWORD',
  'consumer_key' => 'YOUR_CONSUMER_KEY_FROM_EVERNOTE',
  'consumer_secret' => 'YOUR_CONSUMER_SECRECT_FROM_EVERNOTE'
}
```

It would also be nice if this hash could use symbols for keys as the default, but also work with string keys. Thanks!

**Comment by peetucket** [comment]
Yup, good ideas.  I just implemented them, but am having trouble getting the spec tests to run, even after installing the Jeweler gem.  I'm on the latest version of Rails, Ruby 1.9, and just installed the latest rspec.

**Comment by peetucket** [comment]
Error is "no such file to load -- spec/rake/spectask" (line 23 of Rakefile)

**Comment by d1** [comment]
The "no such file to load -- spec/rake/spectask" error is because this gem's specs use rspec1.

I just submitted a pull request to update to rspec2.

**Comment by peetucket** [comment]
Ahh, interesting, good find.

**Comment by peetucket** [comment]
Ahh, interesting, good find.

**Comment by cgs** [comment]
cool, I'll take another look at this.

**Comment by cgs** [comment]
Thanks guys. I'll push a new version of the gem out soon.

**Pull request closed without merging**
